name: Secure Docker Build and Push with SecOps Practices

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  COMMIT_SHA: ${{ github.sha }} # Full commit SHA
  # Using shell command to extract first 8 characters of commit SHA
  COMMIT_TAG: ${{ github.sha }} # We'll handle this in the pipeline

  SLACK_WEBHOOK_URL_GITHUB: ${{ secrets.SLACK_WEBHOOK_GITHUB }}
  BASE_IMAGE: alpine:latest

jobs:
  security-checks:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- SAST: Static Application Security Testing (CodeQL) ---
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: bash

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      # --- SCA: Software Composition Analysis (Dependency Scanning) ---
      - name: Scan Dependencies for Vulnerabilities (Trivy SCA)
        run: |
          trivy fs --exit-code 1 --severity HIGH,CRITICAL .

      # --- Scan for hardcoded secrets (GitLeaks) ---
      - name: Scan for hardcoded secrets
        uses: gitleaks/gitleaks-action@v2
        with:
          fail: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # --- Lint Dockerfile (Hadolint) ---
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3
        with:
          dockerfile: ./Dockerfile

      # --- Generate SBOM (Syft) ---
      - name: Generate SBOM
        uses: anchore/sbom-action@v0.14.3
        with:
          path: .
          format: "spdx-json"
          output-file: "sbom.spdx.json"

      # --- Scan Base Image for Vulnerabilities (Trivy) ---
      - name: Scan Base Image for Vulnerabilities
        run: |
          trivy image --exit-code 1 --severity HIGH,CRITICAL ${{ env.BASE_IMAGE }}

      # --- Notification for Failure ---
      - name: Send Slack notification on failure (GitHub Workflow channel)
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' --data \
          "{\"text\":\":x: Security checks failed in CI/CD pipeline for ${GITHUB_REPOSITORY} on branch ${GITHUB_REF_NAME}\"}" \
          $SLACK_WEBHOOK_URL_GITHUB
          exit 1

  build-and-push:
    runs-on: ubuntu-latest
    needs: security-checks
    if: success()

    permissions:
      contents: write
      packages: write
      security-events: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- Extract First 8 Characters of Commit SHA ---
      - name: Set COMMIT_TAG from commit SHA
        run: echo "COMMIT_TAG=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_ENV

      # --- Docker Build ---
      - name: Build Docker Image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.COMMIT_TAG }} .

      # --- Post-Build Security Scans ---
      - name: Scan Docker Image for Vulnerabilities (Trivy)
        run: |
          trivy image --exit-code 1 --severity HIGH,CRITICAL ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.COMMIT_TAG }}

      # --- Image Signing ---
      - name: Sign Docker Image (Cosign)
        run: |
          cosign sign ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.COMMIT_TAG }}

      # --- Push Image ---
      - name: Push Docker Image to GitHub Container Registry
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.COMMIT_TAG }}

      # --- Notification for Success ---
      - name: Send Slack notification on success (GitHub Workflow channel)
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' --data \
          "{\"text\":\":white_check_mark: Docker image built, scanned, signed, and pushed successfully for ${GITHUB_REPOSITORY} on branch ${GITHUB_REF_NAME}. Image is secure!\"}" \
          $SLACK_WEBHOOK_URL_GITHUB
